from .schemas import ProviderDefinition, ProviderField


PROVIDERS: list[ProviderDefinition] = [
    ProviderDefinition(
        key="hubspot",
        label="HubSpot",
        category="crm",
        description="Connect HubSpot with OAuth and map contacts/companies plus lifecycle, owner, engagement, and churn-related custom properties for scoring.",
        recommended_order=1,
        fields=[
            ProviderField(key="client_id", label="Client ID", required=True, secret=False),
            ProviderField(key="client_secret", label="Client Secret", required=True, secret=True),
            ProviderField(
                key="redirect_uri",
                label="Redirect URI",
                required=True,
                placeholder="http://localhost:3000/integrations/hubspot/callback",
                help_text="This must match the redirect URL configured in your HubSpot app.",
            ),
            ProviderField(key="object_name", label="Object Name", placeholder="contacts", help_text="Usually contacts."),
            ProviderField(key="params", label="Query Params JSON", kind="json", placeholder='{"limit": 100}')
        ],
    ),
    ProviderDefinition(
        key="salesforce",
        label="Salesforce",
        category="crm",
        description="Query lead or contact objects from Salesforce using SOQL.",
        recommended_order=2,
        fields=[
            ProviderField(key="base_url", label="Instance URL", required=True, placeholder="https://your-instance.my.salesforce.com"),
            ProviderField(key="access_token", label="Access Token", required=True, secret=True),
            ProviderField(key="query", label="SOQL Query", required=True, kind="textarea", placeholder="SELECT Id, Name, Company, Email, Title, LeadSource FROM Lead LIMIT 100"),
        ],
    ),
    ProviderDefinition(
        key="dynamics365",
        label="Dynamics 365 Sales",
        category="crm",
        description="Read leads from Microsoft Dynamics 365 Sales via the OData API.",
        recommended_order=3,
        fields=[
            ProviderField(key="base_url", label="Environment URL", required=True, placeholder="https://your-org.crm.dynamics.com"),
            ProviderField(key="access_token", label="Access Token", required=True, secret=True),
            ProviderField(key="object_name", label="Entity Name", placeholder="leads"),
            ProviderField(key="params", label="Query Params JSON", kind="json", placeholder='{"$top": 100}')
        ],
    ),
    ProviderDefinition(
        key="zoho",
        label="Zoho CRM",
        category="crm",
        description="Connect with Zoho OAuth and analyze Leads/Contacts with stages, owner, activity recency, renewal, and churn-signal fields.",
        recommended_order=4,
        fields=[
            ProviderField(
                key="client_id",
                label="Client ID",
                required=False,
                secret=False,
                help_text="Optional if ZOHO_CLIENT_ID is set in the API .env file.",
            ),
            ProviderField(
                key="client_secret",
                label="Client Secret",
                required=False,
                secret=True,
                help_text="Optional if ZOHO_CLIENT_SECRET is set in the API .env file.",
            ),
            ProviderField(
                key="redirect_uri",
                label="Authorized Redirect URI",
                required=True,
                placeholder="http://localhost:8000/api/oauth/zoho/callback",
                help_text="Must match exactly what you registered in Zoho API Console (your backend callback URL).",
            ),
            ProviderField(
                key="zoho_accounts_host",
                label="Zoho accounts host",
                placeholder="accounts.zoho.com",
                help_text="Use accounts.zoho.eu, accounts.zoho.in, etc. if your org is in another data center.",
            ),
            ProviderField(
                key="oauth_scope",
                label="OAuth scopes (space-separated)",
                kind="textarea",
                placeholder="ZohoCRM.modules.leads.READ ZohoCRM.modules.contacts.READ",
                help_text="Requested during Connect Zoho CRM. Add .WRITE scopes only if you need to update records.",
            ),
            ProviderField(key="object_name", label="Module", placeholder="Leads", help_text="CRM module to sync, e.g. Leads or Contacts."),
            ProviderField(key="params", label="Query Params JSON", kind="json", placeholder='{"per_page": 100}'),
        ],
    ),
    ProviderDefinition(
        key="pipedrive",
        label="Pipedrive",
        category="crm",
        description="Read lead or person data from Pipedrive.",
        recommended_order=5,
        fields=[
            ProviderField(key="base_url", label="API Base URL", placeholder="https://your-company.pipedrive.com/api/v1"),
            ProviderField(key="api_key", label="API Token", required=True, secret=True),
            ProviderField(key="object_name", label="Resource", placeholder="leads"),
        ],
    ),
    ProviderDefinition(
        key="freshsales",
        label="Freshsales",
        category="crm",
        description="Read lead records from Freshsales CRM.",
        recommended_order=6,
        fields=[
            ProviderField(key="base_url", label="API Base URL", required=True, placeholder="https://your-domain.myfreshworks.com/crm/sales/api"),
            ProviderField(key="api_key", label="API Key", required=True, secret=True),
            ProviderField(key="object_name", label="Resource", placeholder="leads"),
        ],
    ),
    ProviderDefinition(
        key="mondaycrm",
        label="monday CRM",
        category="crm",
        description="Read monday CRM board items via GraphQL and map columns like owner, stage, health, usage, renewal, and churn-risk notes into scoring signals.",
        recommended_order=7,
        fields=[
            ProviderField(
                key="access_token",
                label="API / OAuth access token",
                required=False,
                secret=True,
                help_text="Optional if MONDAY_API_TOKEN is set in apps/api/.env. Personal API token or OAuth access_token.",
            ),
            ProviderField(
                key="monday_board_ids",
                label="Board IDs (comma-separated)",
                required=False,
                placeholder="5093637072",
                help_text="Default board ID for this workspace. Override with your URL or ID, comma-separated for several boards. Optional if MONDAY_BOARD_IDS is in .env.",
            ),
            ProviderField(
                key="query",
                label="Custom GraphQL query (optional)",
                required=False,
                kind="textarea",
                placeholder="",
                help_text="Leave blank to use Board IDs. If set, must query boards → items_page → items (id, name, column_values).",
            ),
            ProviderField(
                key="params",
                label="Options JSON",
                kind="json",
                placeholder='{"limit": 100}',
                help_text="``limit`` caps items per board (default 100, max 500).",
            ),
        ],
    ),
    ProviderDefinition(
        key="odoo",
        label="Odoo CRM",
        category="crm",
        description="Read CRM leads from Odoo JSON-RPC or REST proxy endpoints.",
        recommended_order=8,
        fields=[
            ProviderField(key="base_url", label="Base URL", required=True, placeholder="https://odoo.company.com"),
            ProviderField(key="api_key", label="API Key or Password", required=True, secret=True),
            ProviderField(key="client_id", label="Database/User", placeholder="db-or-user"),
            ProviderField(key="object_name", label="Model", placeholder="crm.lead"),
        ],
    ),
    ProviderDefinition(
        key="netsuite",
        label="Oracle NetSuite CRM",
        category="enterprise",
        description="Read lead records from NetSuite REST APIs.",
        recommended_order=9,
        fields=[
            ProviderField(key="base_url", label="Account Base URL", required=True),
            ProviderField(key="access_token", label="Access Token", required=True, secret=True),
            ProviderField(key="object_name", label="Record Type", placeholder="lead"),
        ],
    ),
    ProviderDefinition(
        key="oracle_sales",
        label="Oracle Sales",
        category="enterprise",
        description="Read lead and prospect records from Oracle Sales APIs.",
        recommended_order=10,
        fields=[
            ProviderField(key="base_url", label="API Base URL", required=True),
            ProviderField(key="access_token", label="Access Token", required=True, secret=True),
            ProviderField(key="object_name", label="Resource", placeholder="leads"),
        ],
    ),
    ProviderDefinition(
        key="sap_sales_cloud",
        label="SAP Sales Cloud",
        category="enterprise",
        description="Read lead and opportunity records from SAP Sales Cloud.",
        recommended_order=11,
        fields=[
            ProviderField(key="base_url", label="API Base URL", required=True),
            ProviderField(key="access_token", label="Access Token", required=True, secret=True),
            ProviderField(key="object_name", label="Resource", placeholder="LeadCollection"),
        ],
    ),
    ProviderDefinition(
        key="postgres",
        label="Postgres",
        category="database",
        description="Read contact/company/lead rows from Postgres with scoring and churn-analysis columns like lifecycle_stage, engagement_score, and churn_risk.",
        recommended_order=12,
        fields=[
            ProviderField(
                key="connection_url",
                label="Connection URL",
                required=False,
                secret=True,
                placeholder="postgresql+psycopg://local:local@localhost:5434/leadscore_local",
                help_text="Optional if POSTGRES_SOURCE_URL is set in apps/api/.env.",
            ),
            ProviderField(
                key="query",
                label="SQL Query",
                required=False,
                kind="textarea",
                placeholder="select * from contacts order by full_name limit 25",
                help_text="Optional if POSTGRES_SOURCE_QUERY is set in apps/api/.env.",
            ),
        ],
    ),
    ProviderDefinition(
        key="supabase",
        label="Supabase",
        category="database",
        description="Read lead-intelligence rows from Supabase Postgres, including CRM-compatible scoring and churn fields.",
        recommended_order=13,
        fields=[
            ProviderField(
                key="connection_url",
                label="Connection URL",
                required=False,
                secret=True,
                placeholder="postgresql+psycopg://postgres:postgres@localhost:5435/postgres",
                help_text="Optional if SUPABASE_SOURCE_URL is set in apps/api/.env.",
            ),
            ProviderField(
                key="query",
                label="SQL Query",
                required=False,
                kind="textarea",
                placeholder="select * from public.contacts order by full_name limit 25",
                help_text="Optional if SUPABASE_SOURCE_QUERY is set in apps/api/.env.",
            ),
        ],
    ),
    ProviderDefinition(
        key="mysql",
        label="MySQL",
        category="database",
        description="Read lead-intelligence rows directly from MySQL with CRM-compatible scoring and churn-analysis columns.",
        recommended_order=14,
        fields=[
            ProviderField(
                key="connection_url",
                label="Connection URL",
                required=False,
                secret=True,
                placeholder="mysql+pymysql://local:local@localhost:3307/leadscore_local",
                help_text="Optional if MYSQL_SOURCE_URL is set in apps/api/.env.",
            ),
            ProviderField(
                key="query",
                label="SQL Query",
                required=False,
                kind="textarea",
                placeholder="select * from contacts order by full_name limit 25",
                help_text="Optional if MYSQL_SOURCE_QUERY is set in apps/api/.env.",
            ),
        ],
    ),
    ProviderDefinition(
        key="mongodb",
        label="MongoDB",
        category="database",
        description="Read lead documents from MongoDB collections with owner, health, usage, renewal, and churn-risk signals.",
        recommended_order=15,
        fields=[
            ProviderField(
                key="connection_url",
                label="Connection URL",
                required=False,
                secret=True,
                placeholder="mongodb://localhost:27018",
                help_text="Optional if MONGODB_SOURCE_URL is set in apps/api/.env.",
            ),
            ProviderField(
                key="database",
                label="Database",
                required=False,
                placeholder="leadscore_local",
                help_text="Optional if MONGODB_SOURCE_DATABASE is set in apps/api/.env.",
            ),
            ProviderField(
                key="collection",
                label="Collection",
                required=False,
                placeholder="contacts",
                help_text="Optional if MONGODB_SOURCE_COLLECTION is set in apps/api/.env.",
            ),
            ProviderField(
                key="filter",
                label="Filter JSON",
                kind="json",
                placeholder="{}",
                help_text="Optional if MONGODB_SOURCE_FILTER is set in apps/api/.env.",
            )
        ],
    ),
    ProviderDefinition(
        key="dubai_dld_mcp",
        label="Dubai Real Estate MCP",
        category="mcp",
        description="Query Dubai Land Department property transactions and market trends via MCP for real estate search, pricing, and deal analysis.",
        recommended_order=16,
        fields=[
            ProviderField(
                key="query",
                label="Search text",
                kind="textarea",
                placeholder="Marina Gate, JBR, Downtown, recent luxury sales, market pulse",
                help_text="Natural-language property search or market request used by the real_estate_search_agent.",
            ),
            ProviderField(
                key="mcp_tool_name",
                label="MCP tool override",
                placeholder="search_properties",
                help_text="Optional. Defaults to a Dubai-property search tool based on the query, but you can override it.",
            ),
            ProviderField(
                key="params",
                label="Tool arguments JSON",
                kind="json",
                placeholder='{"query": "Marina Gate", "limit": 10}',
                help_text="Optional tool arguments merged with the search text above.",
            ),
            ProviderField(
                key="mcp_command",
                label="MCP command override",
                placeholder="uvx",
                help_text="Optional override. Leave blank to use uvx dld-mcp.",
            ),
            ProviderField(
                key="mcp_args",
                label="MCP args JSON override",
                kind="json",
                placeholder='["dld-mcp"]',
                help_text="Optional override. Leave blank to use the default dld-mcp launcher.",
            ),
        ],
    ),
    ProviderDefinition(
        key="excel",
        label="Excel File",
        category="file",
        description="Upload or reference Excel files with CRM-compatible contact/company fields plus lead-scoring and churn-analysis columns.",
        recommended_order=17,
        fields=[
            ProviderField(
                key="file_path",
                label="File Path",
                required=False,
                placeholder="/absolute/path/to/lead_intelligence_template.xlsx",
                help_text="Optional for browser upload flows. Use when the file already exists on the backend machine.",
            ),
            ProviderField(
                key="sheet_name",
                label="Sheet Name / Index",
                placeholder="contacts",
                help_text="Recommended sheets: contacts, companies, or a combined lead_intelligence sheet.",
            )
        ],
    ),
    ProviderDefinition(
        key="csv",
        label="CSV File",
        category="file",
        description="Upload or reference CSV files with CRM-compatible contact/company fields plus lead-scoring and churn-analysis columns.",
        recommended_order=18,
        fields=[
            ProviderField(
                key="file_path",
                label="File Path",
                required=False,
                placeholder="/absolute/path/to/lead_intelligence_template.csv",
                help_text="Optional for browser upload flows. Use when the file already exists on the backend machine.",
            )
        ],
    ),
]
